site_name: Omar Villafuerte
site_description: Hi! 👋 I'm Omar Villafuerte.
site_url: https://ovillafuerte94.is-a.dev
repo_url: https://github.com/ovillafuerte94
edit_uri: ''

theme:
  name: material
  logo: assets/images/avatar.png
  favicon: assets/images/avatar.png
  features:
    - navigation.tabs
  palette:
    primary: black
    accent: light blue

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - meta
  - toc:
      permalink: 🔗

nav:
  - Home:
      - About me: index.md

copyright: Copyright &copy; Omar Villafuerte

extra_javascript:
  - 'https://unpkg.com/@codersrank/summary@0.9.9/codersrank-summary.min.js'
  - 'https://unpkg.com/@codersrank/activity@0.9.7/codersrank-activity.min.js'
  - 'https://unpkg.com/@codersrank/skills-chart@0.9.10/codersrank-skills-chart.min.js'
  - 'https://unpkg.com/@codersrank/education@0.9.10/codersrank-education.min.js'
  - 'https://unpkg.com/@codersrank/work-experience@0.9.5/codersrank-work-experience.min.js'

extra:
  manifest: manifest.json
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ovillafuerte94
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/ovillafuerte94
      name: GitHub
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/ovillafuerte94
      name: Gitlab
    - icon: fontawesome/solid/code
      link: https://profile.codersrank.io/user/ovillafuerte94
      name: Codersrank
    - icon: fontawesome/brands/dev
      link: https://dev.to/ovillafuerte94
      name: Dev.to
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/5518832/omar-villafuerte
      name: Stack Overflow
    - icon: fontawesome/brands/medium
      link: https://medium.com/@ovillafuerte94
      name: Medium
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ovillafuerte94
      name: Twitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/ovillafuerte94
      name: Telegram
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ovillafuerte94
      name: Facebook
    - icon: fontawesome/solid/paper-plane
      link: mailto:ovillafuerte.94@gmail.com
      name: Gmail
